services:
  emscripten-builder:
    # user: "${UID:-0}:${GID:-0}"
    image: seanmorris/phpwasm-emscripten-builder
    build:
      context: ./
      dockerfile: emscripten-builder.dockerfile
    environment:
      EMCC_CORES: 8
      ENVIRONMENT: ${ENVIRONMENT:-web}
    volumes:
      - ./:/src
      - /tmp/emsdk-cache:/emsdk/upstream/emscripten/cache/
      - ./.cache:/emsdk_portable/.data/cache/asmjs/
    command: [ bash ]
